# Lógica do Segundo Exercício da Apostila

**Aluno:** Rafael Lúcio Negrão Cordeiro<br/>
**Matrícula:** 201310323<br/>
**Disciplina:** CET961 - Engenharia Assistida por Computador

In [30]:
import numpy as np

d = 0.25 # diametro, em cm
E = 3e7  # N / cm²

A = np.pi * (d / 2) ** 2 # cm²

hooke = lambda E, A, L: E * A / L # Lei de Hooke

L1 = 9 # cm
L2 = 12 # cm
L3 = np.sqrt((L1 ** 2) + (L2 ** 2)) # cm

con1 = (1, 3)
con2 = (1, 2)
con3 = (2, 3)

alpha = np.array([np.arccos(L2 / L3), np.arccos(1), np.arccos(0)]) # Graus em radianos

F = 50 # N
Fx = F * np.cos(alpha[0])
Fy = F * np.sin(alpha[0])

#### Compondo o sistema na notaçao matricial $[K_{i}^{(g)}]\{U_{i}^{(g)}\} = \{F_{i}^{(g)}\}$, temos:

$$
\begin{split}
    \overbrace{
        \begin{bmatrix}
            k_{1 x 1 (i)} & k_{1 x 2 (i)} & k_{1 x 3 (i)} & k_{1 x 4 (i)}\\
            k_{2 x 1 (i)} & k_{2 x 2 (i)} & k_{2 x 3 (i)} & k_{2 x 4 (i)}\\
            k_{3 x 1 (i)} & k_{3 x 2 (i)} & k_{3 x 3 (i)} & k_{3 x 4 (i)}\\
            k_{4 x 1 (i)} & k_{4 x 2 (i)} & k_{4 x 3 (i)} & k_{4 x 4 (i)}
        \end{bmatrix}
    }^{[K^{(g)}_i]}
    \overbrace{
        \begin{Bmatrix}
            u_{iX}^E\\
            u_{iY}^E\\
            u_{iX}^D\\
            u_{iY}^D
        \end{Bmatrix}
    }^{\{U^{(g)}_i\}}
    =
    \overbrace{
        \begin{Bmatrix}
            F_{iX}^{E}\\
            F_{iY}^{E}\\
            F_{iX}^{D}\\
            F_{iY}^{D}
        \end{Bmatrix}
    }^{\{F^{(g)}_i\}}\\
    \overbrace{
        \frac{E_iA_i}{L_i}
        \begin{bmatrix}
            \cos^2\alpha_i & \cos\alpha_i\sin\alpha_i & -\cos^2\alpha_i & -\cos\alpha_i\sin\alpha_i\\
            \cos\alpha_i\sin\alpha_i & \sin^2\alpha_i & -\cos\alpha_i\sin\alpha_i & -\sin^2\alpha_i\\
            -\cos^2\alpha_i & -\cos\alpha_i\sin\alpha_i & \cos^2\alpha_i & \cos\alpha_i\sin\alpha_i\\
            \cos\alpha_i\sin\alpha_i & -\sin^2\alpha_i & -\cos\alpha_i\sin\alpha_i & -\sin^2\alpha_i
        \end{bmatrix}
    }^{[K^{(g)}_i]}
    \overbrace{
        \begin{bmatrix}
            \cos\alpha_i & 0\\
            \sin\alpha_i & 0\\
            0 & \cos\alpha_i\\
            0 & \sin\alpha_i
        \end{bmatrix}
        \begin{Bmatrix}
            u_{iX}^E\\
            u_{iX}^D
        \end{Bmatrix}
    }^{\{U^{(g)}_i\}}=
    \overbrace{
        \begin{bmatrix}
            \cos\alpha_i & 0\\
            \sin\alpha_i & 0\\
            0 & \cos\alpha_i\\
            0 & \sin\alpha_i
        \end{bmatrix}
        \begin{Bmatrix}
            F_{iX}^E\\
            F_{iX}^D
        \end{Bmatrix}
    }^{\{F^{(g)}_i\}}
\end{split}
$$

$$
\overbrace{
    \frac{E_iA_i}{L_i}
    \begin{bmatrix}
        \cos^3\alpha_i + \cos\alpha_i\sin^2\alpha_i & -\cos^3\alpha_i - \cos\alpha_i\sin^2\alpha_i\\
        \cos^2\alpha_i\sin\alpha_i + \sin^3\alpha_i & -\cos^2\alpha_i\sin\alpha_i - \sin^3\alpha_i\\
        -\cos^3\alpha_i - \cos\alpha_i\sin^2\alpha_i & \cos^3\alpha_i + \cos\alpha_i\sin^2\alpha_i\\
        \cos^2\alpha_i\sin\alpha_i - \sin^3\alpha_i & -\cos^2\alpha_i\sin\alpha_i - \sin^3\alpha_i
    \end{bmatrix}
    \begin{Bmatrix}
        u_{iX}^E\\
        u_{iX}^D
    \end{Bmatrix}
}^{\{K^{(g)}_i\}\{U^{(g)}_i\}}
=
\overbrace{
        \begin{bmatrix}
            \cos\alpha_i & 0\\
            \sin\alpha_i & 0\\
            0 & \cos\alpha_i\\
            0 & \sin\alpha_i
        \end{bmatrix}
        \begin{Bmatrix}
            F_{iX}^E\\
            F_{iX}^D
        \end{Bmatrix}
}^{\{F^{(g)}_i\}}
$$

Representando em forma de sistema, temos:

$$
\begin{equation}
    \frac{E_iA_i}{L_i}
    x
    \begin{cases}
        (\cos^3\alpha_i + \cos\alpha_i\sin^2\alpha_i)u_{iX}^E - (\cos^3\alpha_i + \cos\alpha_i\sin^2\alpha_i)u_{iX}^D = \cos\alpha_iF_{iX}^E\\
        (\cos^2\alpha_i\sin\alpha_i + \sin^3\alpha_i)u_{iX}^E - (\cos^2\alpha_i\sin\alpha_i + \sin^3\alpha_i)u_{iX}^D = \sin\alpha_iF_{iX}^E\\
        -(\cos^3\alpha_i + \cos\alpha_i\sin^2\alpha_i)u_{iX}^E + (\cos^3\alpha_i + \cos\alpha_i\sin^2\alpha_i)u_{iX}^D = \cos\alpha_iF_{iX}^D\\
        (\cos^2\alpha_i\sin\alpha_i - \sin^3\alpha_i)u_{iX}^E - (\cos^2\alpha_i\sin\alpha_i + \sin^3\alpha_i)u_{iX}^D = \sin\alpha_iF_{iX}^D
    \end{cases}
\end{equation}
$$

Existe uma biblioteca no python dedicada a resolver equações organizadas na forma matricial acima. No pacote numpy, módulo de algebra linear. O código a seguir criará os vetores da matriz acima e executará o módulo de algebra linear do numpy, já entregando os resultados.

In [37]:
from itertools import cycle

# image de conjunto imagem de uma funç~ao
image = [[1, -1, 1, -1]]
image = cycle(image)

for i in alpha:
    # coeffs de coeficientes
    coeffs = np.mat([[np.cos(i) ** 3 + np.cos(i) * (np.sin(i) ** 2), -(np.cos(i) ** 3 + np.cos(i) * (np.sin(i) ** 2)), -np.cos(i) * Fx, 0],
              [np.sin(i) ** 3 + (np.cos(i) ** 2) * np.sin(i), -(np.sin(i) ** 3 + (np.cos(i) ** 2) * np.sin(i)), -np.sin(i) * Fy, 0],
              [-(np.cos(i) ** 3 + np.cos(i) * (np.sin(i) ** 2)), np.cos(i) ** 3 + np.cos(i) * (np.sin(i) ** 2), 0, np.cos(i) * Fx],
              [(np.cos(i) ** 2) * np.sin(i) - np.sin(i) ** 3, -((np.cos(i) ** 2) * np.sin(i) + np.sin(i) ** 3), 0, np.sin(i) * Fy]])
                    
    u = next(image)
    
    print(coeffs)
    
    variaveis = np.linalg.solve(coeffs, u)
#     print('Os resultados são: u2 = %.2em, u3 = %.2em, f1 = %.2eN e f4 = %.2N' % tuple(variaveis))
    print(variaveis)

[[  0.8    -0.8   -32.      0.   ]
 [  0.6    -0.6   -18.      0.   ]
 [ -0.8     0.8     0.     32.   ]
 [  0.168  -0.6     0.     18.   ]]
[-21.70138889 -11.28472222  -0.29166667  -0.22916667]
[[  1.  -1. -40.   0.]
 [  0.  -0.  -0.   0.]
 [ -1.   1.   0.  40.]
 [  0.  -0.   0.   0.]]


LinAlgError: Singular matrix

In [28]:
np.cos(60.* np.pi/180.)

0.5000000000000001

In [34]:
-np.arctan(9 / 12) * 180 / np.pi

-36.86989764584402