# Lógica do Segundo Exercício da Apostila

**Aluno:** Rafael Lúcio Negrão Cordeiro<br/>
**Matrícula:** 201310323<br/>
**Disciplina:** CET961 - Engenharia Assistida por Computador

In [32]:
A1 = 32.3 # cm²
A2 = 38.7 # cm²
A3 = 25.8 # cm²

E1 = 6.9e10  # N / m
E2 = 20.7e10 # N / m
E3 = 20.7e10 # N / m

L1 = 2.54 # m
L2 = 2.54 # m
L3 = 3.59 # m

con1 = (2, 3)
con2 = (1, 2)
con3 = (1, 3)

alpha = np.array([90, 0, 135])

u1 = u3 = 0

#### Podemos definir a lei de Hooke da seguinte forma:

In [2]:
hooke = lambda E, A, L: E * A / L

#### Compondo o sistema na notaçao matricial $[K_{i}^{(g)}]\{U_{i}^{(g)}\} = \{F_{i}^{(g)}\}$, temos:

$$
\begin{split}
    \overbrace{
        \frac{E_iA_i}{L_i}
        \begin{bmatrix}
            \cos^2\alpha_i & \cos\alpha_i\sin\alpha_i & -\cos^2\alpha_i & -\cos\alpha_i\sin\alpha_i\\
            \cos\alpha_i\sin\alpha_i & \sin^2\alpha_i & -\cos\alpha_i\sin\alpha_i & -\sin^2\alpha_i\\
            -\cos^2\alpha_i & -\cos\alpha_i\sin\alpha_i & \cos^2\alpha_i & \cos\alpha_i\sin\alpha_i\\
            \cos\alpha_i\sin\alpha_i & -\sin^2\alpha_i & -\cos\alpha_i\sin\alpha_i & -\sin^2\alpha_i
        \end{bmatrix}
    }^{[K^{(g)}]}
    \overbrace{
        \begin{Bmatrix}
            (u_{i}^E)_X\\
            (u_{i}^E)_Y\\
            (u_{i}^D)_X\\
            (u_{i}^D)_Y
        \end{Bmatrix}
    }^{\{U^{(g)}\}}
    =
    \overbrace{
        \begin{Bmatrix}
            (F_{i}^{(E)})_X\\
            (F_{i}^{(E)})_Y\\
            (F_{i}^{(D)})_X\\
            (F_{i}^{(D)})_Y
        \end{Bmatrix}
    }^{\{F^{(g)}\}}\\
    \overbrace{
        \begin{bmatrix}
            k_{1 x 1 (i)} & k_{1 x 2 (i)} & k_{1 x 3 (i)} & k_{1 x 4 (i)}\\
            k_{2 x 1 (i)} & k_{2 x 2 (i)} & k_{2 x 3 (i)} & k_{2 x 4 (i)}\\
            k_{3 x 1 (i)} & k_{3 x 2 (i)} & k_{3 x 3 (i)} & k_{3 x 4 (i)}\\
            k_{4 x 1 (i)} & k_{4 x 2 (i)} & k_{4 x 3 (i)} & k_{4 x 4 (i)}
        \end{bmatrix}
    }^{[K^{(g)}]}
    \overbrace{
        \begin{Bmatrix}
            (u_{i}^E)_X\\
            (u_{i}^E)_Y\\
            (u_{i}^D)_X\\
            (u_{i}^D)_Y
        \end{Bmatrix}
    }^{\{U^{(g)}\}}
    =
    \overbrace{
        \begin{Bmatrix}
            (F_{i}^{(E)})_X\\
            (F_{i}^{(E)})_Y\\
            (F_{i}^{(D)})_X\\
            (F_{i}^{(D)})_Y
        \end{Bmatrix}
    }^{\{F^{(g)}\}}\\
\end{split}
$$

Representando em forma de sistema, temos:

$$
\begin{equation}
    \begin{cases}
        k_{1 x 1 (i)}(u_{i}^E)_X + k_{1 x 2 (i)}(u_{i}^E)_Y + k_{1 x 3 (i)}(u_{i}^D)_X + k_{1 x 4 (i)}(u_{i}^D)_Y = (F_{i}^{(E)})_X\\
        k_{2 x 1 (i)}(u_{i}^E)_X + k_{2 x 2 (i)}(u_{i}^E)_Y + k_{2 x 3 (i)}(u_{i}^D)_X + k_{2 x 4 (i)}(u_{i}^D)_Y = (F_{i}^{(E)})_Y\\
        k_{3 x 1 (i)}(u_{i}^E)_X + k_{3 x 2 (i)}(u_{i}^E)_Y + k_{3 x 3 (i)}(u_{i}^D)_X + k_{3 x 4 (i)}(u_{i}^D)_Y = (F_{i}^{(D)})_X\\
        k_{4 x 1 (i)}(u_{i}^E)_X + k_{4 x 2 (i)}(u_{i}^E)_Y + k_{4 x 3 (i)}(u_{i}^D)_X + k_{4 x 4 (i)}(u_{i}^D)_Y = (F_{i}^{(D)})_Y
    \end{cases}
\end{equation}
$$

Listando o sistema para cada nó:

$$
\begin{equation}
    i = 1, \alpha = 90
    \begin{cases}
        0(u_{i}^E)_X + 0(u_{i}^E)_Y + 0(u_{i}^D)_X + 0(u_{i}^D)_Y = (F_{i}^{(E)})_X\\
        0(u_{i}^E)_X + (u_{i}^E)_Y + 0(u_{i}^D)_X - (u_{i}^D)_Y = (F_{i}^{(E)})_Y\\
        0(u_{i}^E)_X + 0(u_{i}^E)_Y + 0(u_{i}^D)_X + 0(u_{i}^D)_Y = (F_{i}^{(D)})_X\\
        0(u_{i}^E)_X - (u_{i}^E)_Y + 0(u_{i}^D)_X - (u_{i}^D)_Y = (F_{i}^{(D)})_Y
    \end{cases}\\
    i = 2, \alpha = 0
    \begin{cases}
        (u_{i}^E)_X + 0(u_{i}^E)_Y - (u_{i}^D)_X + 0(u_{i}^D)_Y = (F_{i}^{(E)})_X\\
        0(u_{i}^E)_X + 0(u_{i}^E)_Y + 0(u_{i}^D)_X + 0(u_{i}^D)_Y = (F_{i}^{(E)})_Y\\
        - (u_{i}^E)_X + 0(u_{i}^E)_Y + (u_{i}^D)_X + 0(u_{i}^D)_Y = (F_{i}^{(D)})_X\\
        0(u_{i}^E)_X + 0(u_{i}^E)_Y + 0(u_{i}^D)_X + 0(u_{i}^D)_Y = (F_{i}^{(D)})_Y
    \end{cases}\\
    i = 3, \alpha = 135
    \begin{cases}
        0.5(u_{i}^E)_X - 0.5(u_{i}^E)_Y - 0.5(u_{i}^D)_X + 0.5(u_{i}^D)_Y = (F_{i}^{(E)})_X\\
        - 0.5(u_{i}^E)_X + 0.5(u_{i}^E)_Y + 0.5(u_{i}^D)_X - 0.5(u_{i}^D)_Y = (F_{i}^{(E)})_Y\\
        - 0.5(u_{i}^E)_X + 0.5(u_{i}^E)_Y + 0.5(u_{i}^D)_X - 0.5(u_{i}^D)_Y = (F_{i}^{(D)})_X\\
        - 0.5(u_{i}^E)_X - 0.5(u_{i}^E)_Y + 0.5(u_{i}^D)_X - 0.5(u_{i}^D)_Y = (F_{i}^{(D)})_Y
    \end{cases}
\end{equation}
$$

Existe uma biblioteca no python dedicada a resolver equações organizadas na forma matricial acima. No pacote numpy, módulo de algebra linear. O código a seguir criará os vetores da matriz acima e executará o módulo de algebra linear do numpy, já entregando os resultados.

In [34]:
import numpy as np
from itertools import cycle

# image de conjunto imagem de uma funç~ao
image = [[0, 1, 0, 1], [1, 0, 1, 0], [1, 1, 1, 1]]
image = cycle(image)

for i in np.multiply(np.pi/180, alpha):
    # coeffs de coeficientes
    coeffs = np.array([[np.cos(i) ** 2, np.cos(i) * np.sin(i), - np.cos(i) ** 2, - np.cos(i) * np.sin(i)],
              [np.cos(i) * np.sin(i), np.sin(i) ** 2, - np.cos(i) * np.sin(i), - np.sin(i) ** 2],
              [- np.cos(i) ** 2, - np.cos(i) * np.sin(i), np.cos(i) ** 2, np.cos(i) * np.sin(i)],
              [np.cos(i) * np.sin(i), - np.sin(i) ** 2, - np.cos(i) * np.sin(i), - np.sin(i) ** 2]])
    u = next(image)
    
    print(coeffs)
    
    variaveis = np.linalg.solve(coeffs, u)
#     print('Os resultados são: u2 = %.2em, u3 = %.2em, f1 = %.2eN e f4 = %.2N' % tuple(variaveis))

[[ 3.74939946e-33  6.12323400e-17 -3.74939946e-33 -6.12323400e-17]
 [ 6.12323400e-17  1.00000000e+00 -6.12323400e-17 -1.00000000e+00]
 [-3.74939946e-33 -6.12323400e-17  3.74939946e-33  6.12323400e-17]
 [ 6.12323400e-17 -1.00000000e+00 -6.12323400e-17 -1.00000000e+00]]


LinAlgError: Singular matrix

In [16]:
[1, 2, 3]

[1, 2, 3, 1, 2, 3]

In [28]:
np.cos(60.* np.pi/180.)

0.5000000000000001

In [25]:
np.rad(90)

AttributeError: module 'numpy' has no attribute 'rad'